name: Test

on: [push, pull_request]

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Run unit tests
        run: make test
